# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import metrics_msg_pb2 as metrics__msg__pb2


class QueryManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryMetrics = channel.unary_unary(
                '/metrics_msg.QueryManager/QueryMetrics',
                request_serializer=metrics__msg__pb2.MetricsRequest.SerializeToString,
                response_deserializer=metrics__msg__pb2.MetricsResponse.FromString,
                )


class QueryManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=metrics__msg__pb2.MetricsRequest.FromString,
                    response_serializer=metrics__msg__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metrics_msg.QueryManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueryManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics_msg.QueryManager/QueryMetrics',
            metrics__msg__pb2.MetricsRequest.SerializeToString,
            metrics__msg__pb2.MetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
